# Generated by Django 3.1.5 on 2021-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
