# Generated by Django 3.1.5 on 2021-04-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Authenticate', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CountryMaster_model', to='Master.countrymaster'),
        ),
    ]
